---
title: "final project"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(reticulate)
knitr::knit_engines$set(py = function(options) {
  code <- paste(options$code, collapse = '\n')
  out  <- system2(
    'python', c('-c', shQuote(code)), stdout = TRUE
  )
  knitr::engine_output(options, code, out)
})
py_install('pandas')
```

```{r}
#install.packages("contrib.url")
```

About
===================================== 

Page 2
===================================== 

Row
-----------------------------------------------------------------------

### Chart A

```{r}
library(tidyverse) 
library(readr)
library(plyr)
library(tidyverse)
df <- read_csv(file = '/Users/clara/Downloads/503/finalProj/national-history.csv')
ggplot(data=df)+
  geom_line(mapping=aes(y=negative, x= date,color="negative")) +
  geom_line(mapping=aes(y=positive, x= date,color="positive")) +
  scale_color_manual(values = c(
    'negative' = 'darkblue',
    'positive' = 'red')) +
  labs(color = 'Total test resutls') + ggtitle("Covid-19 test results in 2020")


```
### Chart D
```{r}
df <- read_csv(file = '/Users/clara/Downloads/503/finalProj/covid_us.csv')

cases_by_state <- aggregate(cases ~ state, data = df, FUN = sum)
cases_by_state <- cases_by_state[order(cases_by_state$cases, decreasing = TRUE),]
library(ggplot2)
ggplot(cases_by_state, aes(x = cases, y = reorder(state, cases)), fill="#FF6666")+
  xlab("covid-19 confirmed cases") + ylab("states") + 
    geom_bar(stat = 'identity') +theme_minimal()
coord_flip()



```


Row
-----------------------------------------------------------------------

### Chart B

```{r}
deaths_by_state <- aggregate(deaths ~ state, data = df, FUN = sum)
deaths_by_state <- deaths_by_state[order(deaths_by_state$deaths, decreasing = TRUE),]
ggplot(deaths_by_state, aes(x = deaths, y = reorder(state, deaths)))+
  xlab("covid-19 deaths") + ylab("states") + 
    geom_bar(stat = 'identity') +theme_minimal()
coord_flip()

```

### Chart C

```{r}
library(rjson)
library(plotly)
```


```{r}
df <- read_csv(file = '/Users/clara/Downloads/503/finalProj/covid_us.csv')
url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)
fig <- plot_ly() 
fig <- fig %>% add_trace(
    type="choroplethmapbox",
    geojson=counties,
    locations=df$fips,
    z=df$cases,
    colorscale="Viridis",
    zmin=0,
    zmax=12,
    marker=list(line=list(
      width=0),
      opacity=0.5
    )
  )
fig <- fig %>% layout(
    mapbox=list(
      style="carto-positron",
      zoom =2,
      center=list(lon= -95.71, lat=37.09))
  )
fig
```


Page 3
===================================== 
```{r}
install.packages('network')
```


Row
-----------------------------------------------------------------------

### Chart A
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(network)

viz_df <- read_csv(file = '/Users/clara/Downloads/503/finalProj/network.csv')
sources <- viz_df %>%
  distinct(source) %>%
  rename(label = source)
#distinct(select(df, source))

destinations <- viz_df %>%
  distinct(target) %>%
  rename(label = target)

nodes <- full_join(sources, destinations, by = "label")
nodes <- nodes %>% rowid_to_column("id")

#nodes
per_route <- viz_df 
edges <- per_route %>% 
  left_join(nodes, by = c("source" = "label")) %>% 
  rename(from = id)

edges <- edges %>% 
  left_join(nodes, by = c("target" = "label")) %>% 
  rename(to = id)
edges <- select(edges, from, to, counts)
routes_network <- network(edges, vertex.attr = nodes, matrix.type = "edgelist", ignore.eval = FALSE)
plot(routes_network, vertex.cex = 3)


df_first_35 <- viz_df[1:35, ]
sources35 <- df_first_35 %>%
  distinct(source) %>%
  rename(label = source)
#distinct(select(df, source))

destinations35 <- df_first_35 %>%
  distinct(target) %>%
  rename(label = target)

nodes35 <- full_join(sources35, destinations35, by = "label")
nodes35 <- nodes35 %>% rowid_to_column("id")
per_route35 <- df_first_35
edges35 <- per_route35 %>% 
  left_join(nodes35, by = c("source" = "label")) %>% 
  rename(from = id)

edges35 <- edges35 %>% 
  left_join(nodes35, by = c("target" = "label")) %>% 
  rename(to = id)
edges35 <- select(edges35, from, to, counts)

detach(package:network)
rm(routes_network)
library(igraph)
routes_igraph <- graph_from_data_frame(d = edges35, vertices = nodes35, directed = TRUE)
plot(routes_igraph, edge.arrow.size = 0.2)
plot(routes_igraph, layout = layout_with_graphopt, edge.arrow.size = 0.2)
```


### Chart B
```{r}

# Load
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")

df <- read_csv(file = '/Users/clara/Downloads/503/finalProj/network.csv')
x <- as.vector(as.matrix(df[,c("source", "target")]))
set.seed(1234)
wordcloud(words = x, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

Row
-----------------------------------------------------------------------

### Chart C

### Chart D